#pragma once

#define SCREEN_WIDTH  1024
#define SCREEN_HEIGHT 768
#define SCREEN_VERTICAL_OFFSET (SCREEN_HEIGHT/4)
#define ENTITY_SIZE   30
#define BULLET_SIZE_WIDTH 50
#define BULLET_SIZE_HEIGHT 20

#define TIME_STEP 1000/30
#define DELAY 2

#define LEVEL_COUNT 3

#define GAME_STATE_MENU 1
#define GAME_STATE_PLAY 2
#define GAME_STATE_PAUSE 3
#define GAME_STATE_QUIT 0

#define MENU_STATE_WELCOME 0
#define MENU_STATE_GAME_OVER 1
#define MENU_STATE_VICTORY 2

#define MENU_SELECTED_PLAY 0
#define MENU_SELECTED_QUIT 1

#define ALIEN_DIRECTION_RIGHT 1
#define ALIEN_DIRECTION_LEFT -1

#define ALIEN_VERTICAL_SPEED 40
#define ALIEN_HORIZONTAL_SPEED 8

#define ALIEN_FIRING_DELAY 8000
#define ALIEN_HEALTH 20

#define PLAYER_SPEED 10
#define PLAYER_FIRING_DELAY 1000
#define PLAYER_HEALTH 50

#define PLAYER_VERTICAL_POSITION (SCREEN_HEIGHT - (ENTITY_SIZE * 2))

#define BULLET_SPEED 15

#define GET_RESOURCE_PATH(res_name) "resources/"res_name

#define RED_COLOR { 255,40,40 }
#define WHITE_COLOR { 255,255,255 }
